name: Fed
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - libffi=3.4.4
  - openssl=3.0.16
  - pcre2=10.42
  - pip=25.1
  - python=3.10.16
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==2.2.2
      - ale-py==0.8.1
      - annotated-types==0.7.0
      - atomicwrites==1.4.1
      - attrs==25.3.0
      - box2d-py==2.3.5
      - certifi==2025.4.26
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.2.1
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - contourpy==1.3.2
      - cryptography==44.0.3
      - cycler==0.12.1
      - cython==3.1.1
      - decorator==5.2.1
      - docker-pycreds==0.4.0
      - etils==1.12.2
      - farama-notifications==0.0.4
      - fasteners==0.19
      - filelock==3.13.1
      - flwr==1.18.0
      - fonttools==4.58.0
      - fsspec==2024.6.1
      - future==1.0.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - glfw==2.9.0
      - grpcio==1.71.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==1.1.1
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - iterators==0.0.2
      - jinja2==3.1.4
      - kiwisolver==1.4.8
      - lz4==4.4.4
      - markdown==3.8
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - moviepy==2.2.1
      - mpmath==1.3.0
      - mujoco==2.2.0
      - mujoco-py==2.1.2.14
      - networkx==3.3
      - numpy==2.1.2
      - opencv-python==4.11.0.86
      - packaging==25.0
      - pandas==2.2.3
      - pathspec==0.12.1
      - pillow==11.0.0
      - platformdirs==4.3.8
      - pluggy==1.6.0
      - proglog==0.1.12
      - protobuf==4.25.8
      - psutil==7.0.0
      - py==1.11.0
      - pycparser==2.22
      - pycryptodome==3.23.0
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - pygame==2.1.0
      - pyglet==1.3.3
      - pygments==2.19.1
      - pyopengl==3.1.9
      - pyparsing==3.2.3
      - pytest==7.0.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - rich==13.9.4
      - sentry-sdk==2.29.1
      - setproctitle==1.3.6
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - stable-baselines3==2.6.0
      - swig==4.3.1
      - sympy==1.13.3
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tomli==2.2.1
      - tomli-w==1.2.0
      - tqdm==4.67.1
      - typer==0.12.5
      - typing-extensions==4.12.2
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.4.0
      - wandb==0.19.11
      - werkzeug==3.1.3
      - zipp==3.22.0
prefix: C:\Users\jeff8\anaconda3\envs\Fed
